---

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install python-apt via apt.
  apt: "name={{ item }} state=present"
  with_items:
    - python-apt
    - python3-apt

- name: Install python-pip via apt.
  apt: "name={{ awscli_pip_package }} state=present"

- name: Install awscli via pip.
  pip: "name=awscli version={{ awscli_version }}"
